In [1]:
import pandas as pd
meteor = pd.read_csv('Meteorite_Landings.csv')
meteor = meteor.dropna(subset=['year'])
# meteor.info()

In [2]:
# Remove the nametype field
meteor.drop('nametype',inplace=True,axis=1)
meteor.head()

,name,id,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
0,Aachen,1,L5,21.0,Fell,1880.0,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,H6,720.0,Fell,1951.0,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,EH4,107000.0,Fell,1952.0,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Acapulcoite,1914.0,Fell,1976.0,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,L6,780.0,Fell,1902.0,-33.16667,-64.95000,"(-33.16667, -64.95)"

In [15]:
# Clean the mass (g) field so that there's a default value of 0 where there is no mass listed.

meteor['mass (g)'].fillna(0,inplace=True)
len(meteor[meteor['mass (g)'].isna()])

0

In [4]:
# Store each decade's data in its own data sheet in Excel using pandas. So 1990-1999, 2000-2009, 2010-2019, etc.

meteor['year'].astype(int)
years = meteor['year'].unique()
with pd.ExcelWriter('meteor_by_year.xlsx') as xlsxWriter:
    for year in years:
        if 1990 <= year <= 1999:
            meteor[meteor.year == year].to_excel(xlsxWriter,sheet_name='1990-1999')
        elif 2000 <= year <= 2009:
            meteor[meteor.year == year].to_excel(xlsxWriter,sheet_name='2000-2009')
        elif 2010 <= year <= 2019:
            meteor[meteor.year == year].to_excel(xlsxWriter,sheet_name='2010-2019')

xlsxWriter.save()

H:\anaconda3\lib\site-packages\xlsxwriter\workbook.py:338: UserWarning: Calling close() on already closed file.
  warn("Calling close() on already closed file.")

In [34]:
# Format the date in MM/dd/yyyy with the time in hours:minutes:seconds AM/PM.

meteor = pd.read_csv('Meteorite_Landings.csv')
meteor = meteor.dropna(subset=['year'])
meteor['mass (g)'].fillna(0,inplace=True)
meteor['year'] = meteor['year'].astype(int).astype(str)

print(meteor['year'])

def func(string):
    string = '{}-01-01'.format(string)
    return string

meteor['year'] = meteor['year'].apply(func)

meteor['year']


print(meteor['year'],meteor['year'].astype('datetime64[ns]'))
# pd.to_datetime(meteor.year, format = '%Y')

0        1880
1        1951
2        1952
3        1976
4        1902
         ...
45711    1990
45712    1999
45713    1939
45714    2003
45715    1976
Name: year, Length: 45425, dtype: object

OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1583-01-01 00:00:00

In [ ]:
# Make sure that when the data is imported that all diacritics (umlauts over o's - for example - as in records 44806, 44843-44847 show) are loaded.
for id in range(44843,44874,1):
    print(meteor[meteor.id == id])

                 name     id nametype   recclass  mass (g)   fall    year  \
31056  Österplana 043  44843   Relict  Relict OC       NaN  Found  2002.0

         reclat   reclong           GeoLocation
31056  58.58333  13.43333  (58.58333, 13.43333)
                 name     id nametype   recclass  mass (g)   fall    year  \
31057  Österplana 044  44844   Relict  Relict OC       NaN  Found  2002.0

         reclat   reclong           GeoLocation
31057  58.58333  13.43333  (58.58333, 13.43333)
                 name     id nametype   recclass  mass (g)   fall    year  \
31058  Österplana 045  44845   Relict  Relict OC       NaN  Found  2002.0

         reclat   reclong           GeoLocation
31058  58.58333  13.43333  (58.58333, 13.43333)
                 name     id nametype   recclass  mass (g)   fall    year  \
31059  Österplana 046  44846   Relict  Relict OC       NaN  Found  2002.0

         reclat   reclong           GeoLocation
31059  58.58333  13.43333  (58.58333, 13.43333)
                 name     id nametype   recclass  mass (g)   fall    year  \
31060  Österplana 047  44847   Relict  Relict OC       NaN  Found  2002.0

         reclat   reclong           GeoLocation
31060  58.58333  13.43333  (58.58333, 13.43333)
                        name     id nametype recclass  mass (g)   fall  \
28719  Northwest Africa 4523  44848    Valid  Eucrite     174.0  Found

         year  reclat  reclong GeoLocation
28719  2001.0     NaN      NaN         NaN
Empty DataFrame
Columns: [name, id, nametype, recclass, mass (g), fall, year, reclat, reclong, GeoLocation]
Index: []
                        name     id nametype recclass  mass (g)   fall  \
28535  Northwest Africa 4292  44850    Valid       L6   12000.0  Found

         year  reclat  reclong GeoLocation
28535  2005.0     NaN      NaN         NaN
           name     id nametype recclass  mass (g)   fall    year    reclat  \
1499  Acfer 386  44851    Valid       L5     200.0  Found  2004.0  27.36017

      reclong      GeoLocation
1499      3.7  (27.36017, 3.7)
           name     id nametype recclass  mass (g)   fall    year  reclat  \
1500  Acfer 387  44852    Valid     H4-6     177.0  Found  2004.0  27.558

      reclong      GeoLocation
1500    4.015  (27.558, 4.015)
           name     id nametype recclass  mass (g)   fall    year    reclat  \
1501  Acfer 388  44853    Valid       H4    1072.0  Found  2004.0  27.61667

      reclong          GeoLocation
1501  3.86667  (27.61667, 3.86667)
           name     id nametype recclass  mass (g)   fall    year  reclat  \
1502  Acfer 389  44854    Valid       H5     397.0  Found  2004.0  27.504

      reclong        GeoLocation
1502  3.68167  (27.504, 3.68167)
           name     id nametype recclass  mass (g)   fall    year   reclat  \
1503  Acfer 390  44855    Valid       H4     578.0  Found  2004.0  27.5025

      reclong       GeoLocation
1503    3.693  (27.5025, 3.693)
            name     id nametype recclass  mass (g)   fall    year   reclat  \
1521  Adam Talha  44856    Valid    LL3.2     259.3  Found  2005.0  22.9935

       reclong           GeoLocation
1521 -10.15367  (22.9935, -10.15367)
                  name     id nametype recclass   mass (g)   fall    year  \
1567  Al Haggounia 001  44857    Valid  Aubrite  3000000.0  Found  2006.0

      reclat  reclong    GeoLocation
1567    27.5    -12.5  (27.5, -12.5)
                   name     id nametype recclass  mass (g)   fall    year  \
1640  Allan Hills 06001  44858    Valid       H5     128.1  Found  2006.0

        reclat    reclong             GeoLocation
1640 -76.71695  158.76862  (-76.71695, 158.76862)
                   name     id nametype recclass  mass (g)   fall    year  \
1641  Allan Hills 06002  44859    Valid      H~5     119.2  Found  2006.0

        reclat    reclong             GeoLocation
1641 -76.74253  158.84305  (-76.74253, 158.84305)
                   name     id nametype recclass  mass (g)   fall    year  \
1642  Allan Hills 06003  44860    Valid      H~5      25.0  Found  2006.0

        reclat    reclong             GeoLocation
1642 -76.71128  158.79283  (-76.71128, 158.79283)
                   name     id nametype recclass  mass (g)   fall    year  \
1643  Allan Hills 06004  44861    Valid      H~5      61.7  Found  2006.0

        reclat    reclong             GeoLocation
1643 -76.70522  158.77838  (-76.70522, 158.77838)
                   name     id nametype recclass  mass (g)   fall    year  \
1644  Allan Hills 06005  44862    Valid      H~5       6.0  Found  2006.0

        reclat    reclong             GeoLocation
1644 -76.70522  158.77838  (-76.70522, 158.77838)
                   name     id nametype recclass  mass (g)   fall    year  \
1645  Allan Hills 06006  44863    Valid      H~5     280.9  Found  2006.0

        reclat    reclong             GeoLocation
1645 -76.70558  158.77587  (-76.70558, 158.77587)
                   name     id nametype recclass  mass (g)   fall    year  \
1646  Allan Hills 06007  44864    Valid       H5     226.3  Found  2006.0

        reclat    reclong             GeoLocation
1646 -76.70552  158.77583  (-76.70552, 158.77583)
                   name     id nametype recclass  mass (g)   fall    year  \
1647  Allan Hills 06008  44865    Valid      H~5     120.0  Found  2006.0

        reclat    reclong             GeoLocation
1647 -76.70552  158.77485  (-76.70552, 158.77485)
                   name     id nametype recclass  mass (g)   fall    year  \
1648  Allan Hills 06009  44866    Valid      H~5      28.6  Found  2006.0

        reclat    reclong             GeoLocation
1648 -76.71215  158.77527  (-76.71215, 158.77527)
                   name     id nametype recclass  mass (g)   fall    year  \
1649  Allan Hills 06010  44867    Valid      H~5      1.08  Found  2006.0

        reclat    reclong             GeoLocation
1649 -76.71263  158.77862  (-76.71263, 158.77862)
                   name     id nametype recclass  mass (g)   fall    year  \
1650  Allan Hills 06011  44868    Valid      H~5      24.3  Found  2006.0

        reclat   reclong            GeoLocation
1650 -76.71255  158.7786  (-76.71255, 158.7786)
                   name     id nametype recclass  mass (g)   fall    year  \
1651  Allan Hills 06012  44869    Valid       H5      91.0  Found  2006.0

        reclat    reclong             GeoLocation
1651 -76.71733  158.77398  (-76.71733, 158.77398)
                       name     id nametype   recclass  mass (g)   fall  \
3436  Arabian Peninsula 001  44870    Valid  Diogenite     145.0  Found

        year  reclat  reclong GeoLocation
3436  2006.0     NaN      NaN         NaN
                       name     id nametype recclass  mass (g)   fall    year  \
3437  Arabian Peninsula 002  44871    Valid  Eucrite      54.0  Found  2006.0

      reclat  reclong GeoLocation
3437     NaN      NaN         NaN
                       name     id nametype   recclass  mass (g)   fall  \
3438  Arabian Peninsula 003  44872    Valid  Diogenite      56.0  Found

        year  reclat  reclong GeoLocation
3438  2006.0     NaN      NaN         NaN
                       name     id nametype   recclass  mass (g)   fall  \
3439  Arabian Peninsula 004  44873    Valid  Diogenite      31.0  Found

        year  reclat  reclong GeoLocation
3439  2006.0     NaN      NaN         NaN